name: Setup Go
description: 'Sets up Go environment with dependency caching for faster and more reliable builds'
author: 'Moonrise Labs'

branding:
  icon: 'code'
  color: 'blue'

inputs:
  go-version-file:
    description: 'File containing the Go version to use'
    default: 'go.work'
    required: false
  cache-dependency-path:
    description: 'Path to Go module files for dependency caching'
    default: 'go.work'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
      with:
        go-version-file: ${{ inputs.go-version-file }}
        cache-dependency-path: ${{ inputs.cache-dependency-path }}