name: Lint TypeScript
description: 'Runs code quality checks for TypeScript projects using ESLint'
author: 'Moonrise Labs'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  skip-node-setup:
    description: 'Whether to skip the Node setup step'
    default: 'false'
    required: false
  skip-just-setup:
    description: 'Whether to skip the Just setup step'
    default: 'false'
    required: false
  use-just:
    description: 'Whether to use Just to run linting'
    default: 'false'
    required: false
  just-command:
    description: 'The Just command to run TypeScript linting'
    default: 'lint-ts'
    required: false
  eslint-args:
    description: 'Additional arguments to pass to ESLint'
    default: ''
    required: false
  lint-path:
    description: 'Path to lint with ESLint'
    default: '.'
    required: false
  working-directory:
    description: 'Directory to run linting in'
    default: '.'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Node
      if: ${{ inputs.skip-node-setup != 'true' }}
      uses: moonrise-labs/github-actions/actions/setup-node@main

    - name: Setup Just
      if: ${{ inputs.skip-just-setup != 'true' && inputs.use-just == 'true' }}
      uses: moonrise-labs/github-actions/actions/setup-just@main

    # Just-based linting

    - name: Run Linting with Just
      if: ${{ inputs.use-just == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: just ${{ inputs.just-command }} ${{ inputs.lint-path }} ${{ inputs.eslint-args }}

    # Direct linting

    - name: Run Linting with ESLint
      if: ${{ inputs.use-just != 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: pnpm eslint ${{ inputs.lint-path }} ${{ inputs.eslint-args }}
