name: Build Docker Image
description: Build Docker Image with Docker Buildx

inputs:
  image-name:
    description: The name for the Docker image
    required: true
  image-tag:
    description: The tag for the Docker image
    default: 'latest'
    required: false
  context:
    description: The context to build the Dockerfile in
    required: true
  dockerfile:
    description: The path to the Dockerfile to build
    required: true
  push:
    description: Whether to push the Docker image
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v6
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}