name: Setup Helm
description: Sets up Helm with optional version configuration
author: Moonrise Labs

branding:
  icon: command
  color: blue

inputs:
  helm-version:
    description: The version of Helm to install
    required: false
    default: v3.17.1

runs:
  using: composite
  steps:
    - name: Setup Helm
      uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
      with:
        version: ${{ inputs.helm-version }}