name: Setup Python with uv
description: 'Sets up Python environment with uv package manager for faster, more reliable Python package management'
author: 'Moonrise Labs'

branding:
  icon: 'code'
  color: 'yellow'

inputs:
  python-version-file:
    description: 'File containing the Python version to use'
    default: '.python-version'
    required: false
  uv-version:
    description: 'Version of uv to install'
    default: 'latest'
    required: false
  enable-cache:
    description: 'Whether to enable dependency caching for faster workflow runs'
    default: 'true'
    required: false
  cache-dependency-glob:
    description: 'Glob pattern to use for dependency caching'
    default: 'uv.lock'
    required: false
  install-dependencies:
    description: 'Whether to automatically install dependencies'
    default: 'true'
    required: false
  dev-dependencies:
    description: 'Whether to install development dependencies'
    default: 'false'
    required: false
  extra-dependencies:
    description: 'Whether to install all extras packages'
    default: 'false'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version-file: ${{ inputs.python-version-file }}

    - name: Install uv
      uses: astral-sh/setup-uv@22695119d769bdb6f7032ad67b9bca0ef8c4a174 # v5
      with:
        enable-cache: ${{ inputs.enable-cache }}
        cache-dependency-glob: ${{ inputs.cache-dependency-glob }}
        version: ${{ inputs.uv-version }}

    - name: Install dependencies with uv
      if: ${{ inputs.install-dependencies == 'true' }}
      shell: bash
      run: uv sync ${{ inputs.extra-dependencies == 'true' && '--all-extras' || '' }} ${{ inputs.dev-dependencies == 'true' && '--dev' || '' }}