name: Lint SQL
description: 'Runs code quality checks for SQL files using sqlfluff'
author: 'Moonrise Labs'

branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  skip-python-setup:
    description: 'Whether to skip the Python setup step'
    default: 'false'
    required: false
  skip-just-setup:
    description: 'Whether to skip the Just setup step'
    default: 'false'
    required: false
  use-just:
    description: 'Whether to use Just to run linting'
    default: 'false'
    required: false
  just-command:
    description: 'The Just command to run SQL linting'
    default: 'lint-sql'
    required: false
  sqlfluff-version:
    description: 'Version of sqlfluff to install'
    default: 'latest'
    required: false
  sqlfluff-args:
    description: 'Additional arguments to pass to sqlfluff'
    default: ''
    required: false
  lint-path:
    description: 'Path to lint with sqlfluff'
    default: '.'
    required: false
  working-directory:
    description: 'Directory to run linting in'
    default: '.'
    required: false

runs:
  using: composite
  steps:
    - name: Setup Python with uv
      if: ${{ inputs.skip-python-setup != 'true' }}
      uses: moonrise-labs/github-actions/actions/setup-python@main
      with:
        install-dependencies: 'false'

    - name: Setup Just
      if: ${{ inputs.skip-just-setup != 'true' && inputs.use-just == 'true' }}
      uses: moonrise-labs/github-actions/actions/setup-just@main

    - name: Install sqlfluff
      shell: bash
      run: |
        if [ "${{ inputs.sqlfluff-version }}" = "latest" ]; then
          uv pip install sqlfluff
        else
          uv pip install sqlfluff==${{ inputs.sqlfluff-version }}
        fi

    # Just-based linting

    - name: Run Linting with Just
      if: ${{ inputs.use-just == 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: just ${{ inputs.just-command }} ${{ inputs.lint-path }} ${{ inputs.sqlfluff-args }}

    # Direct linting

    - name: Run Linting with sqlfluff
      if: ${{ inputs.use-just != 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        ARGS="${{ inputs.sqlfluff-args }}"
        uv run sqlfluff lint ${{ inputs.lint-path }} $ARGS
